swagger: "2.0"
info:
   description: "A production ready of XCoin's REST-API"
   version: "1.0.0"
   title: "The Xcoins REST-API"
   contact:
      email: "samanbaboli@gmail.com"
host: "127.0.0.1:3009"
basePath: "/api"
tags:
   - name: "profile"
     description: "Profiles and everything associated with them"
   - name: "favorite"
     description: "Favorites and everything associated with them"
   - name: "simulator"
     description: "Simulators and everything associated with them"

schemes:
   - "http"
paths:
   /profile:
      post:
         tags:
            - "profile"
         summary: "Add a new profile to the database"
         description: ""
         operationId: "newProfile"
         consumes:
            - "application/json"
         produces:
            - "application/json"
         parameters:
            - in: "body"
              name: "body"
              description: "Profile document"
              required: true
              schema:
                 $ref: "#/definitions/Profile"
         responses:
            "201":
               description: "Created Successfuly"
            "400":
               description: "Bad request"
         security:
            - profilestore_auth:
                 - "write:profiles"
                 - "read:profiles"
      put:
         tags:
            - "profile"
         summary: "Update an existing profile"
         description: ""
         operationId: "updateProfile"
         consumes:
            - "application/json"
         produces:
            - "application/json"
         parameters:
            - in: "body"
              name: "body"
              description: "Profile document"
              required: true
              schema:
                 $ref: "#/definitions/Profile"
         responses:
            "400":
               description: "Validation error"
            "404":
               description: "Profile not found"
         
         security:
            - profilestore_auth:
                 - "write:profiles"
                 - "read:profiles"
      get:
         tags:
            - "profile"
         summary: "Get list of Profiles"
         description: ""
         operationId: "findProfiles"
         consumes:
            - "application/json"
            - "application/xml"
         produces:
            - "application/xml"
            - "application/json"
         responses:
            "200":
               description: "OK"
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/Deployment"

   /profile/{profileId}:
      get:
         tags:
            - "profile"
         summary: "Find a Profile by it's ID"
         description: "Returns a single document that contains profile"
         operationId: "findProfileById"
         produces:
            - "application/xml"
            - "application/json"
         parameters:
            - name: "profileId"
              in: "path"
              description: "ID of profile"
              required: true
              type: "objectId"
              format: "int64"
         responses:
            "200":
               description: "successful operation"
               schema:
                  $ref: "#/definitions/Profile"
            "400":
               description: "Valditaion Error"
            "404":
               description: "Profile not found"
       
      post:
         tags:
            - "profile"
         summary: "Updates a profile in the database"
         description: ""
         operationId: "updateProfileWithForm"
         consumes:
            - "application/x-www-form-urlencoded"
         produces:
            - "application/xml"
            - "application/json"
         parameters:
            - name: "profileId"
              in: "path"
              description: "ID of profile that needs to be updated"
              required: true
              type: "number"
              format: "int64"
            - name: "name"
              in: "formData"
              description: "Updated name of the profile"
              required: false
              type: "string"
            - name: "status"
              in: "formData"
              description: "Updated status of the profile"
              required: false
              type: "string"
         responses:
            "405":
               description: "Invalid input"
         security:
            - profilestore_auth:
                 - "write:profiles"
                 - "read:profiles"
      delete:
         tags:
            - "profile"
         summary: "Deletes a profile"
         description: ""
         operationId: "deleteProfile"
         produces:
            - "application/xml"
            - "application/json"
         parameters:
       
            - name: "profileId"
              in: "path"
              description: "Profile id to delete"
              required: true
              type: "number"
              format: "int64"
         responses:
            "400":
               description: "Valditaion Error"
            "404":
               description: "Profile not found"
         security:
            - profilestore_auth:
                 - "write:profiles"
                 - "read:profiles"






   /favorites:
      post:
         tags:
            - "favorite"
         summary: "Add a new favorite to the database"
         description: ""
         operationId: "addFavorite"
         consumes:
            - "application/json"
         produces:
            - "application/json"
         parameters:
            - in: "body"
              name: "body"
              description: "Favorite object that needs to be added to the database"
              required: true
              schema:
                 $ref: "#/definitions/Favorite"
         responses:
            "201":
               description: "Invalid input"
         security:
            - favoritestore_auth:
                 - "write:favorites"
                 - "read:favorites"
      put:
         tags:
            - "favorite"
         summary: "Update an existing favorite"
         description: ""
         operationId: "updateFavorite"
         consumes:
            - "application/json"
         produces:
            - "application/json"
         parameters:
            - in: "body"
              name: "body"
              description: "Favorite object that needs to be added to the database"
              required: true
              schema:
                 $ref: "#/definitions/Favorite"
         responses:
            "400":
               description: "Valditaion Error"
            "404":
               description: "favorite not found"
         
         security:
            - favoritestore_auth:
                 - "write:favorites"
                 - "read:favorites"
      get:
         tags:
            - "favorite"
         summary: "Get All favorite"
         description: ""
         operationId: "getFavorite"
         consumes:
            - "application/json"
            - "application/xml"
         produces:
            - "application/xml"
            - "application/json"
         responses:
            "200":
               description: "OK"
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/Deployment"

   /favorites/{:id}:
      get:
         tags:
            - "favorite"
         summary: "Find favorite by ID"
         description: "Returns a single favorite"
         operationId: "getFavoriteById"
         produces:
            - "application/json"
         parameters:
            - name: ":id"
              in: "path"
              description: "ID of favorite to return"
              required: true
              type: "number"
              format: "int64"
         responses:
            "200":
               description: "successful operation"
               schema:
                  $ref: "#/definitions/Favorite"
            "400":
               description: "Valditaion Error"
            "404":
               description: "Favorite not found"
       
      post:
         tags:
            - "favorite"
         summary: "Updates a favorite in the database"
         description: ""
         operationId: "updateFavoriteWithForm"
         consumes:
            - "application/x-www-form-urlencoded"
         produces:
            - "application/json"
         parameters:
            - name: ":id"
              in: "path"
              description: "ID of favorite that needs to be updated"
              required: true
              type: "number"
              format: "int64"
            - name: "name"
              in: "formData"
              description: "Updated name of the favorite"
              required: false
              type: "string"
            - name: "status"
              in: "formData"
              description: "Updated status of the favorite"
              required: false
              type: "string"
         responses:
            "405":
               description: "Invalid input"
         security:
            - favoritestore_auth:
                 - "write:favorites"
                 - "read:favorites"
      delete:
         tags:
            - "favorite"
         summary: "Deletes a favorite"
         description: ""
         operationId: "deleteFavorite"
         produces:
            - "application/json"
         parameters:
            - name: ":id"
              in: "path"
              description: "Favorite id to delete"
              required: true
              type: "number"
              format: "int64"
         responses:
            "400":
               description: "Valditaion Error"
            "404":
               description: "favorite not found"
         security:
            - favoritestore_auth:
                 - "write:favorites"
                 - "read:favorites"

     
                 



   /simulators:
      post:
         tags:
            - "simulator"
         summary: "Add a new simulator to the database"
         description: ""
         operationId: "addSimulator"
         consumes:
            - "application/json"
         produces:
            - "application/json"
         parameters:
            - in: "body"
              name: "body"
              description: "Simulator object that needs to be added to the database"
              required: true
              schema:
                 $ref: "#/definitions/Simulator"
         responses:
            "201":
               description: "Invalid input"
         security:
            - simulatorstore_auth:
                 - "write:simulators"
                 - "read:simulators"
      put:
         tags:
            - "simulator"
         summary: "Update an existing simulator"
         description: ""
         operationId: "updateSimulator"
         consumes:
            - "application/json"
         produces:
            - "application/json"
         parameters:
            - in: "body"
              name: "body"
              description: "Simulator object that needs to be added to the database"
              required: true
              schema:
                 $ref: "#/definitions/Simulator"
         responses:
            "400":
               description: "Valditaion Error"
            "404":
               description: "simulator not found"
         
         security:
            - simulatorstore_auth:
                 - "write:simulators"
                 - "read:simulators"
      get:
         tags:
            - "simulator"
         summary: "Get All simulator"
         description: ""
         operationId: "getSimulator"
         consumes:
            - "application/json"
         produces:
            - "application/json"
         responses:
            "200":
               description: "OK"
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/Deployment"

   /simulators/{simulatorId}:
      get:
         tags:
            - "simulator"
         summary: "Find simulator by ID"
         description: "Returns a single simulator"
         operationId: "getSimulatorById"
         produces:
            - "application/json"
         parameters:
            - name: "simulatorId"
              in: "path"
              description: "ID of simulator to return"
              required: true
              type: "number"
              format: "int64"
         responses:
            "200":
               description: "successful operation"
               schema:
                  $ref: "#/definitions/Simulator"
            "400":
               description: "Valditaion Error"
            "404":
               description: "Simulator not found"
       
      post:
         tags:
            - "simulator"
         summary: "Updates a simulator in the database"
         description: ""
         operationId: "updateSimulatorWithForm"
         consumes:
            - "application/x-www-form-urlencoded"
         produces:
            - "application/json"
         parameters:
            - name: "simulatorId"
              in: "path"
              description: "ID of simulator that needs to be updated"
              required: true
              type: "number"
              format: "int64"
            - name: "name"
              in: "formData"
              description: "Updated name of the simulator"
              required: false
              type: "string"
            - name: "status"
              in: "formData"
              description: "Updated status of the simulator"
              required: false
              type: "string"
         responses:
            "405":
               description: "Invalid input"
         security:
            - simulatorstore_auth:
                 - "write:simulators"
                 - "read:simulators"
      delete:
         tags:
            - "simulator"
         summary: "Deletes a simulator"
         description: ""
         operationId: "deleteSimulator"
         produces:

            - "application/json"
         parameters:
         
            - name: "simulatorId"
              in: "path"
              description: "Simulator id to delete"
              required: true
              type: "number"
              format: "int64"
         responses:
            "400":
               description: "Valditaion Error"
            "404":
               description: "simulator not found"
         security:
            - simulatorstore_auth:
                 - "write:simulators"
                 - "read:simulators"

                 
definitions:
   Profile:
      type: "object"
      required:
         - "name"
         - "nickname"
         - "email"
         - "capital"
         - "divisa"
         - "preferedCryptoCurrency"
      properties:
         capital:
            type: "number"
            format: "int64"
         name:
            type: "string"
            example: "Saman"
         nickname:
            type: "string"
            example: "Baboli"
         email:
            type: "string"
            example: "samanbaboli@gmail.com"
         divisa:
            type: "string"
            example: "sdfr43fdf"
         preferedCryptoCurrency:
            type: "string"
            example: "ETH"
      xml:
         name: "Profile"

   Favorite:
      type: "object"
      required:
         - "profileId"
         - "name"
         - "favorites"
      properties:
         capital:
            type: "string"
            example: "61bb7930793ff145a04a56fe"
         name:
            type: "string"
            example: "Saman"
         favorites:
            type: "array"
            example: ["ETH","ETH"]
      xml:
         name: "Favourtie"

   Simulator:
      type: "object"
      required:
         - "profileId"
         - "dateRecorded"
         - "cryptoCurrency"
         - "euros"
         - "price"
         - "quantity"
      properties:
         profileId:
            type: "string"
            example: "61bb7930793ff145a04a56fe"
         dateRecorded:
            type: "date"
            example: "2022-01-02T12:01:12.334Z"
         cryptoCurrency:
            type: "string"
            example: "TOMO"
         euros:
            type: "number"
            format: "int64"
         price:
            type: "number"
            format: "int64"
         quantity:
            type: "number"
            format: "int64"
      xml:
         name: "Simulator"
